/* Noah Klein */

enum RPCCommandID {
  SERIAL_PRINT_PAYLOAD = 0x00,

  IS_CONNECTED = 0x01,

  CALIBRATE_IMU = 0x02,
  GET_IMU_CALIBRATION_PROGRESS = 0x03,
  RESET_TRACKING = 0x04,
  GET_STATUS = 0x05,

  GET_OFFSET = 0x06,
  SET_OFFSET = 0x07,

  GET_POSE = 0x08,
  GET_POSE_STD = 0x09,

  GET_VELOCITY = 0x0A,
  GET_VELOCITY_STD = 0x0B,

  GET_ACCELERATION = 0x0C,
  GET_ACCELERATION_STD = 0x0D,

  GET_POS_VEL_ACC = 0x0E,
  GET_POS_VEL_ACC_STD = 0x0F,
  GET_POS_VEL_ACC_AND_STD = 0x10,
};
